[package]
name = "passwort_manager"
version = "0.1.0"
authors = ["Tom Paßberg"]
edition = "2021"
build = "build.rs"

[build-dependencies]
slint-build = "1.4.1" 

[dependencies]
slint = "1.4.1"
copypasta = "0.10.1"
magic-crypt = "3.1.13"
