import { Button, VerticalBox, LineEdit, HorizontalBox, ListView, CheckBox, StandardListView } from "std-widgets.slint";

export struct DataItem  {
    platform: string,
    password: string,
}

export component AppWindow inherits Window {
    in property <[DataItem]> data_model: [];
    callback add-to-database(string, string);
    callback copy-password-to-clipboard(string);
    callback delete-from-database(string);
    title: "Passwort Manager";
    HorizontalBox {
        VerticalBox {
            width: 450px;
            alignment: center;
            padding-right: 30px;
            padding-left: 10px;
            spacing: 30px;
            Text {
                text: "Neuen Eintrag erstellen";
                font-size: 30px;
                padding-bottom: 30px;
                horizontal-alignment: center;
            }

            platform_input := LineEdit {  
                font-size: 14px;
                height: 40px;
                placeholder-text: "Name der Platform";
            }

            password_input := LineEdit {       
                font-size: 14px;
                height: 40px;
                input-type: password;
                placeholder-text: "Passwort";
            }

            CheckBox {
                text: "Passwort anzeigen";
                toggled => {
                    if (self.checked) {
                        password_input.input-type = InputType.text;
                    } else {
                        password_input.input-type = InputType.password;
                    }
                }
            }

            Button {
                primary: true;
                text: "Passwort speichern";
                height: 60px;
                clicked => {
                    root.add_to_database(platform-input.text, password-input.text);
                    platform-input.text = "";
                    password-input.text = "";
                }
            }
        }
        VerticalBox {
            width: 820px;
            height: 500px;
            spacing: 30px;
            Text {
                text: "Deine Passwörter";
                font-size: 30px;
                horizontal-alignment: center;
            }
            list-view := ListView {
                for item in root.data_model: Rectangle {
                    height: 50px;
                    HorizontalLayout {
                        spacing: 10px;
                        Text { 
                            width: 210px;
                            height: 40px;
                            vertical-alignment: center;
                            text: item.platform;
                            font-size: 20px; 
                        }
                        pw_field := LineEdit {
                            width: 200px;
                            height: 40px;
                            read-only: true;
                            text: item.password;
                            input-type: password;
                            font-size: 14px;
                        }
                        pw_button := Button {
                            text: "Anzeigen"; 
                            width: 100px;
                            height: 40px;
                            primary: true;
                            clicked => {
                                if (pw_field.input-type == InputType.password) {
                                    pw_field.input-type = InputType.text;
                                    pw_button.text = "Verbergen";
                                } else {
                                    pw_field.input-type = InputType.password;
                                    pw_button.text = "Anzeigen";
                                }
                            }
                        }
                        Button {
                            text: "Passwort kopieren"; 
                            width: 150px;
                            height: 40px;
                            primary: true;
                            clicked => {
                                root.copy-password-to-clipboard(item.password);
                            }
                        }
                        Button {
                            text: "Löschen"; 
                            width: 100px;
                            height: 40px;
                            clicked => {
                                if (self.text == "Löschen") {
                                    self.text = "Bestätigen"
                                } else {
                                    root.delete_from_database(item.platform);
                                }
                            }
                        }
                    }    
                } 
            }  
        }
    }
}