import { Button, VerticalBox, LineEdit, HorizontalBox, ListView, CheckBox, StandardListView } from "std-widgets.slint";

export struct DataItem  {
    platform: string,
    password: string,
}

import { CheckBox, StandardListView, StyleMetrics } from "std-widgets.slint";
import { StandardTableView } from "std-widgets.slint";
import { SideBar } from "./sidebar.slint";

export component AppWindow inherits Window {
    in property <[DataItem]> data_model: [
        {platform: "Facebook", password: "123456"},
        {platform: "Instagram", password: "123456"}
    ];
    callback add-to-database(string, string);
    callback copy-password-to-clipboard(string);
    callback delete-from-database(string);
    callback clear-clipboard();
    width: 1030px;
    preferred-height: 600px;
    title: @tr("Passwort Manager");

    HorizontalLayout {
        side-bar := SideBar {
            model: [@tr("Menu" => "Passwort Liste"), @tr("Menu" => "Neuen Eintrag erstellen")];
        }  

        if(side-bar.current-item == 0) : VerticalBox {
            spacing: 10px;
            padding-left: 30px;
            VerticalBox {
                alignment: center;
                height: 50px;
                Text {
                    text: "Deine Passwörter";
                    font-size: 30px;
                    horizontal-alignment: center;
                }
            }
            
            list-view := ListView {
                for item in root.data_model: Rectangle {
                    
                    height: 50px;
                    HorizontalLayout {
                        spacing: 10px;
                        Text { 
                            width: 210px;
                            height: 40px;
                            vertical-alignment: center;
                            text: item.platform;
                            font-size: 20px; 
                        }
                        pw_field := LineEdit {
                            width: 200px;
                            height: 40px;
                            horizontal-alignment: center;
                            read-only: true;
                            text: item.password;
                            input-type: password;
                        }
                        pw_button := Button {
                            text: "Anzeigen"; 
                            width: 100px;
                            height: 40px;
                            primary: true;
                            clicked => {
                                if (pw_field.input-type == InputType.password) {
                                    pw_field.input-type = InputType.text;
                                    pw_button.text = "Verbergen";
                                } else {
                                    pw_field.input-type = InputType.password;
                                    pw_button.text = "Anzeigen";
                                }
                            }
                        }
                        Button {
                            text: "Passwort kopieren"; 
                            width: 150px;
                            height: 40px;
                            primary: true;
                            clicked => {
                                root.copy-password-to-clipboard(item.password);
                            }
                        }
                        Button {
                            text: "Löschen"; 
                            width: 100px;
                            height: 40px;
                            clicked => {
                                if (self.text == "Löschen") {
                                    self.text = "Bestätigen"
                                } else {
                                    root.delete_from_database(item.platform);
                                }
                            }
                        }
                    }    
                } 
            }
            HorizontalBox {
                alignment: center;
                Button {
                    text: "Zwischenablage leeren";
                    primary: true;
                    height: 40px;
                    width: 200px;
                    clicked => {
                        root.clear-clipboard();
                    }                
                }
            }
        }
        if(side-bar.current-item == 1) : VerticalBox {
            alignment: center;
            spacing: 30px;
            padding-left: 200px;
            padding-right: 200px;
            Text {
                text: "Neuen Eintrag erstellen";
                font-size: 30px;
                padding-bottom: 30px;
                horizontal-alignment: center;
            }
    
            platform_input := LineEdit {  
                height: 40px;
                placeholder-text: "Name der Platform";
            }
    
            password_input := LineEdit {       
                height: 40px;
                input-type: password;
                placeholder-text: "Passwort";
            }
    
            CheckBox {
                text: "Passwort anzeigen";
                toggled => {
                    if (self.checked) {
                        password_input.input-type = InputType.text;
                    } else {
                        password_input.input-type = InputType.password;
                    }
                }
            }
    
            Button {
                primary: true;
                text: "Passwort speichern";
                height: 60px;
                clicked => {
                    root.add_to_database(platform-input.text, password-input.text);
                    platform-input.text = "";
                    password-input.text = "";
                }
            }
        }
    }
}